uses prLink instead of prNumber
The following error occured in vercel logs when trying to run
`/dep-graph all` and this commit attempts to fix it

```
received issue comment event: 5313a0b0-ea84-11eb-9476-5e66546e3b95
commenting dependency graph for all changes
Error occured in "issue_comment handler: ReferenceError: prLink is not defined
    at subCommandHandler (/var/task/slash_commands.js:113:13)
    at Object.handle (/var/task/slash_commands.js:41:11)
    at handleSlashCommands (/var/task/slash_commands.js:14:26)
    at /var/task/issue_comment.js:18:11
    at /var/task/node_modules/@octokit/webhooks/event-handler/receive.js:45:14
    at async Promise.all (index 0)"
2021-07-22T00:32:42.034Z	f6a5fcaf-5ebb-4aff-b435-aebff96864c4	ERROR	ERROR:  Error: Webhook handler error
    at /var/task/node_modules/@octokit/webhooks/event-handler/receive.js:58:19 {
  errors: [
    ReferenceError: prLink is not defined
        at subCommandHandler (/var/task/slash_commands.js:113:13)
        at Object.handle (/var/task/slash_commands.js:41:11)
        at handleSlashCommands (/var/task/slash_commands.js:14:26)
        at /var/task/issue_comment.js:18:11
        at /var/task/node_modules/@octokit/webhooks/event-handler/receive.js:45:14
        at async Promise.all (index 0) {
      event: [Object]
    }
  ]
}
```